import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/navbar";
import Footer from "@/components/footer";
import { ClerkProvider } from "@clerk/nextjs";
import { Poppins } from "next/font/google";

const poppins = Poppins({
  subsets: ["latin"], // Optimized subset
  weight: ["300", "400", "500", "600", "700"], // Include the weights you need
  variable: "--font-poppins", // Define a CSS variable for global use
});



export const metadata: Metadata = {
  title: "Avion",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${poppins.variable} antialiased`}
        >   
              <Navbar />
              {children}
              <Footer />
        </body>
      </html>
    </ClerkProvider>
  );
}