import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/navbar";
import Footer from "@/components/footer";
import { ClerkProvider } from "@clerk/nextjs";
import { Poppins } from "next/font/google";
import { Analytics } from "@vercel/analytics/react"

const poppins = Poppins({
  subsets: ['latin'], 
  weight: ['400', '600'], // Choose weights you need
  style: ['normal', 'italic'], // Optional styles
  display: 'swap'
})



export const metadata: Metadata = {
  title: "Avion",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
         className={poppins.className}
        >   
              <Navbar />
              {children}
              <Footer />
              <Analytics />
        </body>
      </html>
    </ClerkProvider>
  );
}