// import type { Metadata } from "next";

// import Navbar from "@/components/navbar";
// import Footer from "@/components/footer";
import { WishlistProvider } from "@/context/WishListContext";// Import WishlistProvider
import { CartProvider } from "@/context/CartContext";
import {
  ClerkProvider,
  SignInButton,
  SignedIn,
  SignedOut,
  UserButton
} from '@clerk/nextjs'

// export const metadata: Metadata = {
//   title: "Avion",
//   description: "Generated by create next app",
// };

export default function Login() {
  return (
    <ClerkProvider>
    <html lang="en">
      <body>
        <SignedOut>
          <SignInButton />
        </SignedOut>
        <SignedIn>
          <UserButton />
        </SignedIn>
        {/* <CartProvider> */}
          {/* <WishlistProvider> */}
            {/* <Navbar /> */}
        {/* {children} */}
        {/* <Footer /> */}
          {/* </WishlistProvider>
        </CartProvider> */}
      </body>
    </html>
  </ClerkProvider>
  );
}
